# Generated by Django 3.1.7 on 2021-11-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211103_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='advisor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='advisor_pic_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='u_name',
            field=models.CharField(max_length=50),
        ),
    ]
